version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: myusern8n
      POSTGRES_PASSWORD: mypasswordn8n
      POSTGRES_DB: mydbn8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=https://n8nencasa.duckdns.org
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8nencasa.duckdns.org
      - GENERIC_TIMEZONE=Europe/Berlin
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/n8n/.n8n

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin1
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "p4ssw0rd"
    ports:
      - "8200:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  n8n_data:
  pgadmin_data:
