version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
