version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
    networks:
      - my-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - my-network

  nginx:
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
