---
- name: Deploy Docker containers
  hosts: all
  become: yes
  vars:
    db_name: mydbn8n
    db_user: myusern8n
    db_password: mypasswordn8n
    db_host: "{{ ansible_host }}"
    db_port: 5432
    jwt_secret: your_jwt_secret
    node_env: production

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
        dest: /usr/local/bin/docker-compose
        mode: "u+x"

    - name: Copy docker-compose.yml to the host
      copy:
        src: ../docker-compose.yaml
        dest: /home/ubuntu/docker-compose.yaml

    - name: Create .env file for the backend
      copy:
        content: |
          DB_NAME={{ db_name }}
          DB_USER={{ db_user }}
          DB_PASSWORD={{ db_password }}
          DB_HOST={{ db_host }}
          DB_PORT={{ db_port }}
          DB_DIALECT=postgres
          JWT_SECRET={{ jwt_secret }}
          PORT=5050
        dest: /home/ubuntu/.env

    - name: Start Docker containers
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu
