name: Terraform and Ansible Workflow

on:
  push:
    branches:
      - actions-Ansible

jobs:
  terraform-vpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: actions-Ansible  # Apunta a la rama correcta

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform_setup/VPC

      - name: Terraform Format
        run: terraform fmt
        working-directory: ./terraform_setup/VPC

      - name: Terraform Format Check
        run: terraform fmt --check
        working-directory: ./terraform_setup/VPC

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform_setup/VPC

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform_setup/VPC

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform_setup/VPC

  terraform-ec2:
    runs-on: ubuntu-latest
    needs: terraform-vpc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: actions-Ansible  # Apunta a la rama correcta

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform_setup/EC2

      - name: Terraform Format Check
        run: terraform fmt
        working-directory: ./terraform_setup/EC2

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform_setup/EC2

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform_setup/EC2

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform_setup/EC2

      - name: Show Terraform Output
        run: terraform output -json
        working-directory: ./terraform_setup/EC2

      - name: Extract IP addresses
        id: extract_ip
        run: |
         IP_ADDRESSES=$(echo '${{ steps.terraform_output.outputs.instance_ip }}' | jq -r '.[]')
         echo "EC2_IPS=$IP_ADDRESSES" >> $GITHUB_ENV
        working-directory: ./terraform_setup/EC2

  ansible-deploy:
    runs-on: ubuntu-latest
    needs: terraform-ec2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: actions-Ansible

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Add SSH key for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Disable SSH Host Key Checking
        run: echo "Host *\nStrictHostKeyChecking no\nUserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/hosts.ini ansible/playbook.yml
